/// Flutter icons IconTabbar
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconTabbar
///      fonts:
///       - asset: fonts/IconTabbar.ttf
///
///
///
import 'package:flutter/widgets.dart';

class IconTabbar {
  IconTabbar._();

  static const _kFontFam = 'IconTabbar';
  static const _kFontPkg = null;

  static const IconData homeduotone =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bellduotone =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eventdisable =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingdisablecopy =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
